apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "sqlpad.fullname" . }}
  labels:
    app: {{ template "sqlpad.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "sqlpad.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ template "sqlpad.fullname" . }}
      volumes:
        - name: {{ template "sqlpad.name" . }}
          persistentVolumeClaim:
            claimName: {{ template "sqlpad.name" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: Always
          env:
            - name: GOOGLE_CLIENT_ID
              value: "{{ .Values.google_client_id }}"
            - name: GOOGLE_CLIENT_SECRET
              value: "{{ .Values.google_client_secret }}"
            - name: PUBLIC_URL
              value: "{{ .Values.public_url }}"
            - name: DISABLE_USERPASS_AUTH
              value: "true"
            - name: WHITELISTED_DOMAINS
              value: "{{ .Values.whitelisted_domains }}"
          volumeMounts:
            - name: {{ template "sqlpad.name" . }}
              mountPath: /var/lib/sqlpad
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
