kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "sqlpad.name" . }}
  #annotations:
  #  volume.beta.kubernetes.io/storage-class: managedssd
  labels:
    app: {{ template "sqlpad.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
